### PR TITLE
Add Arabic docs

### PR DESCRIPTION
**Pull request by MDslash**
Waiting the integration of the Arabic template into Obsidian to update the images and ensure that certain terms are appropriately named.

### CODE REVIEW

**Comment by marcusolsson** [comment]
@MDslash This uses `ar` as a language code. I know there are different variants of arabic. Do we need to add a country code, for example `ar-eg`? Is there a "standard" Arabic?

**Comment by MDslash** [comment]
No country code is needed. MSA (Modern Standard Arabic) is universally understood by Arabic speakers from any country that uses Arabic.

**Comment by marcusolsson** [comment]
Unfortunately, Obsidian Publish doesn't yet support right-to-left languages like Arabic, which means the docs wouldn't be displayed properly. I'm afraid we need to pause this PR until we can support RTL.

**Comment by MDslash** [comment]
It's disappointing, but I'm hopeful they'll address this soon.

**Comment by ericaxu** [comment]
Maybe we can support RTL through supplying a `publish.css` file? What level of RTL should we support? @marcusolsson

**Comment by MDslash** [comment]
Can I continue working on the translation and PRs? @marcusolsson

**Comment by marcusolsson** [comment]
@MDslash I've been working on a RTL layout for Publish. Before translating more docs, could you check whether https://publish.obsidian.md/help-ar displays properly for you?

**Comment by MDslash** [comment]
Yes, the RTL display is working fine, but the note names in the graph view should have RTL direction.

I've made some changes in `publish.css` to improve it further.

Can we replace the text "help-ar" at the top-right with "مساعدة Obsidian"? The word "مساعدة" on the right side.

**Comment by ericaxu** [comment]
> Can we replace the text "help-ar" at the top-right with "مساعدة Obsidian"? The word "مساعدة" on the right side.

Not sure I see the same thing. Can you take a screenshot?

This is what I see at the top-right corner:

image

**Comment by MDslash** [comment]
Yes, I see the same thing as well. I suggest replacing "help-ar" with "مساعدة Obsidian," like this:

image

**Comment by ericaxu** [comment]
> Yes, I see the same thing as well. I suggest replacing "help-ar" with "مساعدة Obsidian," like this:
> 
> image

Just updated! I've merged this docs and updated the site. For any other things please open new issues & PRs. Thanks!

**Pull request merged**
