### PR TITLE
Reflect the removal of translucency from Windows 

### PR DESCRIPTION
**Pull request by colintedford**
Update to reflect the removal of translucency from Windows.

### CODE REVIEW

**Comment by sigrunixia** [comment]
Do you think its worth mentioning that it was removed from windows, and suggest alternatives?

**Comment by colintedford** [comment]
Could be! Maybe a little callout to mention it was removed (callout itself to be removed after some period of time when the change is less new). Other than a theme that recently added some kind of support I don't know what the alternatives are.

**Comment by sigrunixia** [comment]
How about this update, @colintedford ?

**Comment by colintedford** [comment]
Looks good to me.

**Comment by liamcain** [comment]
> Should the functionality be restored in Electron, it will be re-integrated into Obsidian

Can we remove this bit?

**Comment by sigrunixia** [comment]
> > Should the functionality be restored in Electron, it will be re-integrated into Obsidian
> 
> Can we remove this bit?

Done. I guess that is too much of a promise. :)

**Pull request merged**
