### PR TITLE
Starting translation of Persian (fa) language. 

### PR DESCRIPTION
**Pull request by zachshirow**
Adding myself as translator in credits of /en and /fa

Previous pull request had some issues regarding the internal links. I had accidentally opened the root folder instead of the language folder. 

Please kindly verify this matter and accept the pull request if possible. 

I will continue translating bits and pieces of the docs in the following days.

Sorry I'm new to this and I'm learning to work with git as I go. 

I'll be in your care. 

Thanks, 
Zachary

### CODE REVIEW

**Comment by zachshirow** [comment]
Also please note that the Persian docs need to be in RTL direction. Could that be handled by the obsidian publication? I'm guessing there needs to be some css snippets or some plugins that could support this feature. Thanks a lot.

**Comment by ericaxu** [comment]
We have some tweaks on RTL, see https://publish.obsidian.md/help-ar

We can add the same `publish.css` to the Persian site as well.

**Comment by zachshirow** [comment]
> We have some tweaks on RTL, see https://publish.obsidian.md/help-ar
> 
> We can add the same `publish.css` to the Persian site as well.

That sounds great, thank you!

**Comment by ericaxu** [comment]
Let me know when this is ready to be merged!

**Comment by zachshirow** [comment]
Sure thing. I only made this pull request to let you know that I started the translation. You can delete this one id you want. I'll make another pull request when I'm mostly finished.

**Comment by zachshirow** [comment]
You can merge this one by the way if it won't make a difference. I can create another pull request in a few days when I'm mostly finished.

**Comment by zachshirow** [comment]
> ok I'll merge this then!

Cool thanks

**Pull request merged**
