### PR TITLE
Extends Daily Note organisation tip to explain folder structure and custom folders

### PR DESCRIPTION
**Pull request by XylotrupesGideon**
This extends the tip of the Daily Notes formatting help to explain how to automatically create a folder structure for a journal.

Most users will want to use the Daily Notes as a journal. So they create many notes that need to be organized.

The tip now explains how to automatically include a folder structure and a link to more help about specific formating.

It also shows how to create files in a custom folder (which took me a lot of googling to find out)

### CODE REVIEW

**Comment by sigrunixia** [comment]
It's close, but I think we need some rewording for use in the help docs.

What do you think of something like this?

CleanShot 2023-09-27 at 22 16 27@2x

```md
> [!tip] If you prefer to have your daily notes in a separate folder, you can set the <u>New file location</u> under plugin options to change where Obsidian creates new daily notes.

> [!example]- Automated note sorting
> You can automatically organize your daily notes into folders using the **New File Location** feature. For instance, if you set the file location as `Journal/YYYY/MMMM/YYYY-MMM-DD`, your notes will be created as `Journal/2023/January/2023-Jan-01`. 
> 
> You can explore more formatting options on the [momentJS](https://momentjs.com/docs/#/displaying/format/) documentation site.
```

If you like it, or have any other suggestions, feel free to update your commit so I can add it in. :)

**Comment by XylotrupesGideon** [comment]
Yeah that is probably better but the "Journal" needs to be in brackets otherwise it the "a" and "l" will be converted like this:

image

if it is in brackets this does not happen 
image

**Comment by sigrunixia** [comment]
Good Point! I forgot about the AL portion.

**Comment by sigrunixia** [comment]
Merging in. Thank you! ❤️

**Pull request merged**
