### PR TITLE
Update Vault is just a local folder.md

### PR DESCRIPTION
**Pull request by ambassadorJ**

### CODE REVIEW

**Comment by ambassadorJ** [comment]
For consistency, changed "I" to "we"

**Comment by ericaxu** [comment]
Thanks! What did you change on line 23 (last line) btw? @ambassadorJ

**Comment by ambassadorJ** [comment]
No changes on the last line. I don't know why it got flagged as changed.

**Comment by ericaxu** [comment]
> @ericaxu No changes on the last line. I don't know why it got flagged as changed.

Probably just some line ending character change. Will merge.

**Pull request merged**
