### PR TITLE
Update Korean docs

### PR DESCRIPTION
**Pull request by cherojeong**
I've translated entire docs as Korean in obsidian-help, To keep consistency with English Heading and File Name (.md) , I kept Heading and File name as English. It would be better to find and translate from English doc's updated contents later and make internal links with heading.

 - Added ko language to README.md
 - kept Credits document as English.

When I checked obsidian-translation repository, there is ko.json file waiting one of pull requests.
for example. translation of "publish" can be "게시" instead of "출판" in some of cases. it is more precise. but it is not updated yet. so my translation was done based on current translation as "출판". In korean , publish word can be taken either  releasing the book or showing the contents on website or something like that.

### CODE REVIEW

**Comment by sigrunixia** [comment]
Hello @cherojeong 

Do you have any more updates you want to add before this is merged in?

**Comment by cherojeong** [comment]
Hello sigrunixia

No I don't have it. If there is no issue to merge in master, when it would be merged in ? but If there is something to add on your side. please let me know

**Comment by sigrunixia** [comment]
It will be merged... right now! Muahahaha. 👀

**Comment by sigrunixia** [comment]
And as an update, @cherojeong, the site is now published. https://publish.obsidian.md/help-ko/Home

**Pull request merged**
