### PR TITLE
Big Rename.

### PR DESCRIPTION
**Pull request by AliKhomami**
I've renamed most of the files and folders.

### CODE REVIEW

**Comment by ericaxu** [comment]
Hi, thanks for doing this! Do you want to translate the contents in the same PR as well? Or a different PR?

**Comment by AliKhomami** [comment]
Hello. Please merge all the commits in this PR first. I will continue translating the content and will open another PR later. Many thanks.

**Comment by ericaxu** [comment]
Sorry to say there seem to be some conflicts right now. Do you think there's any chance you can resolve them?

**Comment by AliKhomami** [comment]
It seems to be resolved now.

**Pull request merged**
